export const storeURL = '/'
export const profileURL = '/profile'
export const favoriteURL = '/favorite'
export const basketURL = '/basket'
export const devicePageURL = '/device/'
export const typePageURL = '/type/'
export const brandPageURL = '/brand/'
export const searchPageURL = '/search/'
